### ISSUE TITLE
badge

### ISSUE THREAD

**Issue by abubakaristiak** [Thinkright20/Profile-Badges#258]
which is the most powerful badge in GitHub?

**Comment by rubypoddar** [comment]
# Sync Badges

By incorporating Snyk, your project benefits from automatic vulnerability scans, fixes, and pull requests, ensuring a higher level of security and stability. The Snyk GitHub badge prominently displays the vulnerability state of the latest commit on the default branch, providing immediate visibility into the project's security health. This proactive approach not only helps maintain code quality but also reassures contributors and users about the project's commitment to security best practices.

**Comment by abubakaristiak** [comment]
How can I get this batch?

**Comment by rubypoddar** [comment]
## Adding a Snyk Badge to Your Project

your project's security by adding a Snyk badge that displays its vulnerability status. Follow these steps to integrate Snyk with your GitHub repository:

1. **Sign Up for Snyk:**
   - Visit [Snyk](https://snyk.io/) and create an account.

2. **Connect to GitHub:**
   - In Snyk, navigate to the "Projects" tab.
   - Click "Add Project" and select "GitHub."
   - Authorize Snyk to access your GitHub repositories.

3. **Select Your Repository:**
   - Choose the repository `rubypoddar/DeepFace-Recognition` to scan.
   - Snyk will automatically perform a vulnerability scan on the repository.

4. **Get the Badge:**
   - After the scan, go to your project in Snyk.
   - Click on the "Badges" tab and copy the provided Markdown code for the badge.

5. **Add the Badge to Your README:**
   - Open your repository on GitHub.
   - Edit the `README.md` file.
   - Paste the badge code at the top or in a suitable location.
   - Commit the changes.

Example badge code for your repository:
---
[![Known Vulnerabilities](https://snyk.io/test/github/rubypoddar/DeepFace-Recognition/badge.svg)](https://snyk.io/test/github/rubypoddar/DeepFace-Recognition)
![Snyk Vulnerabilities](https://img.shields.io/badge/Snyk-Vulnerabilities-green?style=for-the-badge&logo=snyk&labelColor=black&color=4c1&logoColor=white)
