### ISSUE TITLE
Add Snyk Badge to Display Vulnerability Status

### ISSUE THREAD

**Issue by rubypoddar** [Thinkright20/Profile-Badges#259]
By incorporating Snyk, your project benefits from automatic vulnerability scans, fixes, and pull requests, ensuring a higher level of security and stability. The Snyk GitHub badge prominently displays the vulnerability state of the latest commit on the default branch, providing immediate visibility into the project's security health. This proactive approach not only helps maintain code quality but also reassures contributors and users about the project's commitment to security best practices.

Author: @abubakaristiak

**Comment by abubakaristiak** [comment]
I sincerely appreciate your helpful information. It's quite beneficial.
@rubypoddar
